### ISSUE TITLE
Issue About Us

### ISSUE THREAD

**Issue by arghasatriya** [ekapratama363/wj_property#23]
![image](https://user-images.githubusercontent.com/48237863/99372381-a88de400-28f2-11eb-9cc7-ea485dda1e78.png)

![image](https://user-images.githubusercontent.com/48237863/99372463-c65b4900-28f2-11eb-8939-7121d7c336a2.png)

Tidak perlu ada video di About Us. Video di hilangkan, termasuk di backend nya.

**Comment by arghasatriya** [comment]
![image](https://user-images.githubusercontent.com/48237863/99372920-6618d700-28f3-11eb-9b8a-533b20f8e521.png)

@ekapratama363 ka, design COUNSELOR nya dibuat 1 aja ka.
Referensi dari file html yang gua kasih (about.php)

![image](https://user-images.githubusercontent.com/48237863/99372879-5ac5ab80-28f3-11eb-8d8a-e9cd4efb5585.png)

**Comment by w4hyuhdy** [comment]
hide video dibackend sudah, sudah saya request pull
